import { DebugReport, CheckResult, Recommendation } from '../../types';

/**
 * Generates a Markdown-formatted diagnostic report from a DebugReport.
 */
export const formatReportAsMarkdown = (report: DebugReport): string => {
  const lines: string[] = [];

  lines.push('# BlockTrace Diagnostic Report');
  lines.push('');
  lines.push(`**Job ID:** \`${report.job_id}\``);
  lines.push(`**Target:** \`${report.target}\``);
  lines.push(`**Generated:** ${report.generated_at}`);
  lines.push(`**Execution Time:** ${report.execution_time_ms}ms`);
  lines.push('');

  // Overall summary
  const statusEmoji = report.summary === 'PASS' ? '✅' : report.summary === 'WARN' ? '⚠️' : '❌';
  lines.push(`## ${statusEmoji} Overall: ${report.summary} (Score: ${report.overall_score}/100)`);
  lines.push('');

  // Individual checks
  lines.push('## Check Results');
  lines.push('');

  const checkEntries: [string, CheckResult | undefined][] = [
    ['CAP Integration', report.checks.cap_integration],
    ['Settlement', report.checks.settlement],
    ['A2A Composability', report.checks.a2a_composability],
  ];

  for (const [name, check] of checkEntries) {
    if (!check) continue;

    const icon = check.status === 'PASS' ? '✅' : check.status === 'WARN' ? '⚠️' : '❌';
    lines.push(`### ${icon} ${name} — ${check.status} (${check.score}/100)`);
    lines.push('');
    lines.push(check.details);
    lines.push('');

    if (check.errors && check.errors.length > 0) {
      lines.push('**Errors:**');
      for (const err of check.errors) {
        lines.push(`- ${err}`);
      }
      lines.push('');
    }
  }

  // Recommendations
  if (report.recommendations.length > 0) {
    lines.push('## Recommendations');
    lines.push('');

    for (const rec of report.recommendations) {
      const priorityIcon =
        rec.priority === 'CRITICAL' ? '🔴' :
        rec.priority === 'HIGH' ? '🟠' :
        rec.priority === 'MEDIUM' ? '🟡' : '🟢';

      lines.push(`### ${priorityIcon} [${rec.priority}] ${rec.check}`);
      lines.push('');
      lines.push(`**Issue:** ${rec.issue}`);
      lines.push('');
      lines.push(`**Fix:** ${rec.fix}`);
      if (rec.docs_url) {
        lines.push('');
        lines.push(`**Docs:** ${rec.docs_url}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Report generated by BlockTrace v2.0.0 — Agent ID: ${report.agent_id}*`);

  return lines.join('\n');
};

/**
 * Builds a DebugReport from check results.
 */
export const buildReport = (params: {
  job_id: string;
  target: string;
  checks: {
    cap_integration?: CheckResult;
    settlement?: CheckResult;
    a2a_composability?: CheckResult;
  };
  recommendations: Recommendation[];
  executionStartTime: number;
}): DebugReport => {
  const { job_id, target, checks, recommendations, executionStartTime } = params;

  const allChecks = Object.values(checks).filter(Boolean) as CheckResult[];

  // Determine overall status
  const summary: DebugReport['summary'] = allChecks.some(c => c.status === 'FAIL')
    ? 'FAIL'
    : allChecks.some(c => c.status === 'WARN')
    ? 'WARN'
    : 'PASS';

  // Calculate weighted average score
  const scores = allChecks.map(c => c.score);
  const overall_score = scores.length > 0
    ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length)
    : 0;

  return {
    agent_id: 'BlockTrace_v2',
    job_id,
    target,
    summary,
    overall_score,
    checks,
    recommendations,
    generated_at: new Date().toISOString(),
    execution_time_ms: Date.now() - executionStartTime,
  };
};
